import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


REPORT_OUTPUT_DIR = Path("reports/output")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate matplotlib charts for report output files or metadata JSON files."
    )
    parser.add_argument(
        "--metadata",
        type=Path,
        help="Path to a report metadata JSON file generated by the backend.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        help="Optional path to a CSV or XLSX report output file.",
    )
    parser.add_argument(
        "--report",
        choices=["customer-master", "contact-coverage", "kyc-expiry"],
        help="Pick the latest run for a report from reports/output.",
    )
    parser.add_argument(
        "--all-latest",
        action="store_true",
        help="Generate charts for the latest metadata file of every report type.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    if args.all_latest:
        for report_name in ["customer-master", "contact-coverage", "kyc-expiry"]:
            metadata_path = find_latest_metadata(report_name)
            if metadata_path is None:
                print(f"Skipping {report_name}: no metadata files found.")
                continue
            generate_visualizations(metadata_path, None)
        return

    metadata_path = args.metadata
    if args.report:
        metadata_path = find_latest_metadata(args.report)
        if metadata_path is None:
            raise FileNotFoundError(f"No metadata files found for report: {args.report}")

    if metadata_path is None:
        raise ValueError("Provide --metadata, --report, or --all-latest.")

    generate_visualizations(metadata_path, args.input)


def find_latest_metadata(report_name: str) -> Path | None:
    report_dir = REPORT_OUTPUT_DIR / report_name
    if not report_dir.exists():
        return None

    metadata_files = sorted(report_dir.glob("*.json"), key=lambda path: path.stat().st_mtime, reverse=True)
    return metadata_files[0] if metadata_files else None


def generate_visualizations(metadata_path: Path, input_path: Path | None):
    metadata = load_json(metadata_path)
    report_name = metadata["reportName"]
    run_id = metadata["runId"]
    df = load_dataframe(metadata, input_path)

    if df.empty:
        print(f"No rows available for {report_name} run {run_id}.")
        return

    output_dir = metadata_path.parent / "visualizations" / run_id
    output_dir.mkdir(parents=True, exist_ok=True)

    if report_name == "customer-master":
        visualize_customer_master(df, output_dir)
    elif report_name == "contact-coverage":
        visualize_contact_coverage(df, output_dir)
    elif report_name == "kyc-expiry":
        visualize_kyc_expiry(df, output_dir)
    else:
        visualize_generic(df, output_dir, report_name)

    print(f"Saved charts to: {output_dir}")


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def load_dataframe(metadata: dict, input_path: Path | None) -> pd.DataFrame:
    source_path = input_path or resolve_output_path(metadata)
    if source_path is not None and source_path.exists():
        suffix = source_path.suffix.lower()
        if suffix == ".csv":
            return pd.read_csv(source_path)
        if suffix == ".xlsx":
            return pd.read_excel(source_path)

    preview_rows = metadata.get("previewRows", [])
    return pd.DataFrame(preview_rows)


def resolve_output_path(metadata: dict) -> Path | None:
    output_file = metadata.get("outputFile")
    if not output_file:
        return None
    return Path(output_file)


def visualize_customer_master(df: pd.DataFrame, output_dir: Path):
    save_count_plot(
        df["customer_status"],
        "Customer Status Distribution",
        "Customer Status",
        "Customers",
        output_dir / "customer_status_distribution.png",
    )
    save_count_plot(
        df["country_of_origin"],
        "Country of Origin Distribution",
        "Country",
        "Customers",
        output_dir / "country_distribution.png",
        top_n=10,
    )
    save_count_plot(
        df["preferred_language"],
        "Preferred Language Distribution",
        "Language",
        "Customers",
        output_dir / "preferred_language_distribution.png",
        top_n=10,
    )


def visualize_contact_coverage(df: pd.DataFrame, output_dir: Path):
    save_count_plot(
        df["coverage_status"],
        "Coverage Status Distribution",
        "Coverage Status",
        "Customers",
        output_dir / "coverage_status_distribution.png",
    )

    plt.figure(figsize=(8, 5))
    df["active_contact_count"] = pd.to_numeric(df["active_contact_count"], errors="coerce").fillna(0)
    counts = df["active_contact_count"].value_counts().sort_index()
    counts.plot(kind="bar", color="#1f77b4")
    plt.title("Active Contact Count")
    plt.xlabel("Active Contact Count")
    plt.ylabel("Customers")
    plt.tight_layout()
    plt.savefig(output_dir / "active_contact_count.png", dpi=150)
    plt.close()

    availability = pd.DataFrame(
        {
            "Email Available": pd.to_numeric(df["has_email"], errors="coerce").fillna(0).sum(),
            "Phone Available": pd.to_numeric(df["has_phone"], errors="coerce").fillna(0).sum(),
        },
        index=["Customers"],
    ).T
    plt.figure(figsize=(8, 5))
    availability.plot(kind="bar", legend=False, color=["#2ca02c", "#ff7f0e"])
    plt.title("Contact Availability")
    plt.xlabel("Contact Type")
    plt.ylabel("Customers")
    plt.tight_layout()
    plt.savefig(output_dir / "contact_availability.png", dpi=150)
    plt.close()


def visualize_kyc_expiry(df: pd.DataFrame, output_dir: Path):
    save_count_plot(
        df["proof_status"],
        "KYC Proof Status Distribution",
        "Proof Status",
        "Customers",
        output_dir / "proof_status_distribution.png",
    )
    save_count_plot(
        df["proof_type"].fillna("MISSING"),
        "Proof Type Distribution",
        "Proof Type",
        "Customers",
        output_dir / "proof_type_distribution.png",
    )

    if "proof_end_date" in df.columns:
        end_dates = pd.to_datetime(df["proof_end_date"], errors="coerce")
        valid_dates = end_dates.dropna()
        if not valid_dates.empty:
            reference_date = valid_dates.min().normalize()
            days_until_expiry = (valid_dates - reference_date).dt.days
            plt.figure(figsize=(8, 5))
            plt.hist(days_until_expiry, bins=min(8, max(3, len(days_until_expiry))), color="#d62728", edgecolor="white")
            plt.title("Proof Expiry Spread")
            plt.xlabel("Days From Earliest Proof End Date")
            plt.ylabel("Documents")
            plt.tight_layout()
            plt.savefig(output_dir / "proof_expiry_spread.png", dpi=150)
            plt.close()


def visualize_generic(df: pd.DataFrame, output_dir: Path, report_name: str):
    for column in df.columns[:3]:
        if df[column].dtype == "object":
            save_count_plot(
                df[column],
                f"{report_name}: {column} distribution",
                column,
                "Rows",
                output_dir / f"{column}_distribution.png",
            )


def save_count_plot(series, title: str, xlabel: str, ylabel: str, output_path: Path, top_n: int | None = None):
    counts = series.fillna("MISSING").astype(str).value_counts()
    if top_n is not None:
        counts = counts.head(top_n)

    plt.figure(figsize=(9, 5))
    counts.sort_values(ascending=False).plot(kind="bar", color="#4c78a8")
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.xticks(rotation=25, ha="right")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


if __name__ == "__main__":
    main()
